name: souma
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 24.13.0

environment:
  sdk: '>=3.1.0-315.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  charset_converter: ^2.1.2
  pull_to_refresh: ^2.0.0
  easy_localization: ^3.0.3
  turn_page_transition: ^0.3.0
  custom_clippers: ^2.0.0
  ai_barcode_scanner: ^3.4.1
  platform_device_id: ^1.0.1
  flutter_barcode_scanner: ^2.0.0
  sliding_up_panel2: ^3.3.0+1
  rotated_corner_decoration: ^2.1.0+1
  url_launcher: ^6.2.2
  audioplayers: ^5.2.1
  map_launcher: ^3.1.0
  flutter_svg: # only if you want to use icons as they are svgs

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_app_name:
  name: "souma"

flutter_launcher_name:
  name: "souma"
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
  assets: [assets/images/, assets/langs/, assets/audio/]
